// --users--
// POST  "/api/users" sign up
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "cha3bi@gmail.com", 
    "password" : "adfasdfasdf"
}

### -- get User info --
POST http://localhost:3000/api/users/me
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3LCJ1c2VybmFtZSI6Im11c3RhcGhhQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiJ9LCJpYXQiOjE3NzU3NTQ0MjQsImV4cCI6MTc3NTc1NDQ1NH0.nLHrx6QcDIig72eoZ8wQGy__-UI4HvWmagy-PkDd6OY

###
// --admin--
POST http://localhost:3000/api/users
Content-Type: application/x-www-form-urlencoded

username=mustapha@gmail.com&password=blogAdmin

###
// --posts--
// GET "/api/posts"
GET http://localhost:3000/api/posts

// -- get post with its comments
// GET "/api/posts/:postId"
###
GET http://localhost:3000/api/posts/3
// POST "/api/posts/:postId/comments" create comment 
###
POST http://localhost:3000/api/posts/3/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJ1c2VybmFtZSI6InJvdWliaUJlbGtAZ21haWwuY29tIiwicm9sZSI6IlJlYWRlciJ9LCJpYXQiOjE3NjY4NTY4MzV9.VPuquom9ulODqzSve4U_mFWFvrTsZw9rVXLGjl4xepY
Content-Type: application/json

{
   "text" : "comment 1"   
}
###
// -- admin route --
POST http://localhost:3000/api/admin/auth
Content-Type: application/json

{
    "username": "mustapha@gmail.com", 
    "password": "blogAdmin"
}

// POST "/api/posts" admin create a post
###
POST http://localhost:3000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3LCJ1c2VybmFtZSI6Im11c3RhcGhhQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiJ9LCJpYXQiOjE3NjY4Mzk3ODh9.few50pGXZ9B7Hva4LQCPg6L4Q6elzCOX9UGTfVtRqnE
Content-Type: application/json

{
    "username":"mustapha@gmail.com", 
    "title":"first post by mosuta",
    "published": false, 
    "text": "hi hi capten", 
    "thumbnailUrl": "url",  
    "authorId": 6
}


// --auth--
// POST "/api/auth/profile" login
###
POST http://localhost:3000/api/auth/profile
Content-Type: application/json

{
    "username": "cha3bi@gmail.com", 
    "password": "asdfasdf"
}

###
// POST "/api/auth/logout" logout
POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJ1c2VybmFtZSI6InJvdWliaUJlbGtAZ21haWwuY29tIiwicm9sZSI6IlJlYWRlciJ9LCJpYXQiOjE3NzA0NzU3MDgsImV4cCI6MTc3MTM3NTcwOH0.VQb5aBygMTPZGk7EFgpkYeUZhPFXz_molMderOm7rKM

###
POST http://localhost:3000/api/auth/refresh




